// ── Cloud Security Mock Data ────────────────────────────────────────────────
// Set USE_MOCK_DATA to true for offline development.
// Set to false when connecting to the live FastAPI backend.

import type { Finding, CloudResource, ServiceSummary, CloudAccount, DashboardData } from "./types";

export const USE_MOCK_DATA = true;

// ── Mock Accounts ──────────────────────────────────────────────────────────

export const MOCK_ACCOUNTS: CloudAccount[] = [
  {
    id: "acct-001",
    account_id: "491827364051",
    name: "Xenkrypt Production",
    provider: "aws",
    role_arn: "arn:aws:iam::491827364051:role/CSPMScanRole",
    external_id: "cspm-ext-prod-a1b2c3",
    environment: "production",
    regions: ["us-east-1", "eu-west-1"],
    status: "connected",
    created_at: "2025-11-15T08:30:00Z",
    updated_at: "2026-02-22T14:12:00Z",
    last_scan_at: "2026-02-22T14:12:00Z",
  },
  {
    id: "acct-002",
    account_id: "738291054623",
    name: "Xenkrypt Staging",
    provider: "aws",
    role_arn: "arn:aws:iam::738291054623:role/CSPMScanRole",
    external_id: "cspm-ext-stg-d4e5f6",
    environment: "staging",
    regions: ["us-east-1"],
    status: "connected",
    created_at: "2025-12-03T10:15:00Z",
    updated_at: "2026-02-21T09:45:00Z",
    last_scan_at: "2026-02-21T09:45:00Z",
  },
];

// ── Mock Resources ─────────────────────────────────────────────────────────

export const MOCK_RESOURCES: CloudResource[] = [
  {
    id: "res-001",
    resource_id: "arn:aws:s3:::xenkrypt-prod-assets",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "us-east-1",
    tags: { Environment: "production", Team: "platform", CostCenter: "eng-001" },
    is_public: false,
    encrypted: true,
    raw_data: { Versioning: true, LoggingEnabled: true, ObjectLockEnabled: false },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-002",
    resource_id: "arn:aws:s3:::xenkrypt-user-uploads",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "us-east-1",
    tags: { Environment: "production", Team: "backend" },
    is_public: true,
    encrypted: true,
    raw_data: { Versioning: false, LoggingEnabled: true, ObjectLockEnabled: false },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-003",
    resource_id: "arn:aws:s3:::xenkrypt-logs-archive",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "eu-west-1",
    tags: { Environment: "production", Team: "security" },
    is_public: false,
    encrypted: false,
    raw_data: { Versioning: true, LoggingEnabled: false, LifecyclePolicies: 2 },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-004",
    resource_id: "i-0a7b3c9d2e1f4a5b6",
    resource_type: "AWS::EC2::Instance",
    service: "ec2",
    region: "us-east-1",
    tags: { Name: "api-server-01", Environment: "production", Role: "app-server" },
    is_public: false,
    encrypted: true,
    raw_data: { InstanceType: "m5.xlarge", State: "running", VpcId: "vpc-0abc123def", SubnetId: "subnet-0a1b2c3d", SecurityGroups: ["sg-0a1b2c3d4e"] },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-005",
    resource_id: "i-0c8d4e5f6a7b8c9d0",
    resource_type: "AWS::EC2::Instance",
    service: "ec2",
    region: "us-east-1",
    tags: { Name: "worker-node-03", Environment: "production", Role: "worker" },
    is_public: false,
    encrypted: true,
    raw_data: { InstanceType: "c5.2xlarge", State: "running", VpcId: "vpc-0abc123def", SubnetId: "subnet-0e5f6a7b" },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-006",
    resource_id: "i-0e1f2a3b4c5d6e7f8",
    resource_type: "AWS::EC2::Instance",
    service: "ec2",
    region: "eu-west-1",
    tags: { Name: "bastion-eu", Environment: "production", Role: "bastion" },
    is_public: true,
    encrypted: true,
    raw_data: { InstanceType: "t3.micro", State: "running", VpcId: "vpc-0def456abc", PublicIp: "54.72.31.198" },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-007",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-primary",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    tags: { Environment: "production", Team: "data" },
    is_public: false,
    encrypted: true,
    raw_data: { Engine: "postgresql", EngineVersion: "15.4", DBInstanceClass: "db.r6g.xlarge", MultiAZ: true, StorageEncrypted: true, BackupRetentionDays: 30 },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-008",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-analytics",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    tags: { Environment: "production", Team: "analytics" },
    is_public: false,
    encrypted: false,
    raw_data: { Engine: "mysql", EngineVersion: "8.0.35", DBInstanceClass: "db.m5.large", MultiAZ: false, StorageEncrypted: false, BackupRetentionDays: 7 },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-009",
    resource_id: "arn:aws:lambda:us-east-1:491827364051:function:xenkrypt-auth-handler",
    resource_type: "AWS::Lambda::Function",
    service: "lambda",
    region: "us-east-1",
    tags: { Environment: "production", Team: "auth" },
    is_public: false,
    encrypted: null,
    raw_data: { Runtime: "nodejs20.x", MemorySize: 256, Timeout: 30, LastModified: "2026-02-18T11:20:00Z" },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-010",
    resource_id: "arn:aws:lambda:us-east-1:491827364051:function:xenkrypt-event-processor",
    resource_type: "AWS::Lambda::Function",
    service: "lambda",
    region: "us-east-1",
    tags: { Environment: "production", Team: "platform" },
    is_public: false,
    encrypted: null,
    raw_data: { Runtime: "python3.12", MemorySize: 512, Timeout: 120, LastModified: "2026-02-20T08:15:00Z" },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-011",
    resource_id: "arn:aws:iam::491827364051:user/deploy-bot",
    resource_type: "AWS::IAM::User",
    service: "iam",
    region: null,
    tags: { ManagedBy: "terraform" },
    is_public: null,
    encrypted: null,
    raw_data: { MFAEnabled: false, AccessKeysActive: 2, LastActivity: "2026-02-22T10:30:00Z", PasswordLastUsed: null },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-012",
    resource_id: "arn:aws:iam::491827364051:user/admin-sourish",
    resource_type: "AWS::IAM::User",
    service: "iam",
    region: null,
    tags: {},
    is_public: null,
    encrypted: null,
    raw_data: { MFAEnabled: true, AccessKeysActive: 1, LastActivity: "2026-02-22T13:45:00Z", PasswordLastUsed: "2026-02-22T09:00:00Z" },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-013",
    resource_id: "vpc-0abc123def",
    resource_type: "AWS::EC2::VPC",
    service: "vpc",
    region: "us-east-1",
    tags: { Name: "xenkrypt-prod-vpc", Environment: "production" },
    is_public: null,
    encrypted: null,
    raw_data: { CidrBlock: "10.0.0.0/16", EnableDnsSupport: true, EnableDnsHostnames: true, FlowLogsEnabled: true },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-014",
    resource_id: "sg-0a1b2c3d4e",
    resource_type: "AWS::EC2::SecurityGroup",
    service: "vpc",
    region: "us-east-1",
    tags: { Name: "api-sg", Environment: "production" },
    is_public: null,
    encrypted: null,
    raw_data: { InboundRules: 5, OutboundRules: 2, AllowsAllInbound: false, OpenPorts: [443, 8080] },
    last_seen: "2026-02-22T14:12:00Z",
  },
  {
    id: "res-015",
    resource_id: "sg-0f9e8d7c6b",
    resource_type: "AWS::EC2::SecurityGroup",
    service: "vpc",
    region: "us-east-1",
    tags: { Name: "bastion-sg", Environment: "production" },
    is_public: null,
    encrypted: null,
    raw_data: { InboundRules: 2, OutboundRules: 1, AllowsAllInbound: false, OpenPorts: [22] },
    last_seen: "2026-02-22T14:12:00Z",
  },
];

// ── Mock Service Summary ───────────────────────────────────────────────────

export const MOCK_SERVICE_SUMMARY: ServiceSummary[] = [
  { service: "s3", count: 3, public_count: 1, unencrypted_count: 1 },
  { service: "ec2", count: 3, public_count: 1, unencrypted_count: 0 },
  { service: "rds", count: 2, public_count: 0, unencrypted_count: 1 },
  { service: "lambda", count: 2, public_count: 0, unencrypted_count: 0 },
  { service: "iam", count: 2, public_count: 0, unencrypted_count: 0 },
  { service: "vpc", count: 3, public_count: 0, unencrypted_count: 0 },
];

// ── Mock Dashboard Data ────────────────────────────────────────────────────

export const MOCK_DASHBOARD_DATA: DashboardData = {
  security_score: 72,
  total_alerts: 38,
  alerts_by_severity: {
    critical: 3,
    high: 8,
    medium: 15,
    low: 7,
    info: 5,
  },
  compliance_status: {
    cis_aws: { pass: 142, fail: 18, muted: 3, total: 163, score: 87 },
    soc2: { pass: 88, fail: 12, muted: 0, total: 100, score: 88 },
    pci_dss: { pass: 65, fail: 9, muted: 1, total: 75, score: 87 },
    hipaa: { pass: 48, fail: 7, muted: 2, total: 57, score: 84 },
    nist_800_53: { pass: 112, fail: 22, muted: 4, total: 138, score: 81 },
  },
  asset_inventory: [
    { name: "s3", value: 3, types: [{ name: "Bucket", count: 3 }] },
    { name: "ec2", value: 3, types: [{ name: "Instance", count: 3 }] },
    { name: "rds", value: 2, types: [{ name: "DBInstance", count: 2 }] },
    { name: "lambda", value: 2, types: [{ name: "Function", count: 2 }] },
    { name: "iam", value: 2, types: [{ name: "User", count: 2 }] },
    { name: "vpc", value: 3, types: [{ name: "VPC", count: 1 }, { name: "SecurityGroup", count: 2 }] },
  ],
  total_resources: 15,
  last_scan: "2026-02-22T14:12:00Z",
  recent_findings: [],
};

// ── Mock Findings ──────────────────────────────────────────────────────────

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "find-001",
    account_id: "acct-001",
    check_id: "s3_bucket_public_access",
    resource_id: "arn:aws:s3:::xenkrypt-user-uploads",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "us-east-1",
    title: "S3 Bucket has public access enabled",
    status: "fail",
    severity: "critical",
    compliance_type: "CIS AWS",
    description: "The S3 bucket 'xenkrypt-user-uploads' has public access enabled. Public buckets can be accessed by anyone on the internet, potentially exposing sensitive data.",
    recommendation: "Enable S3 Block Public Access settings at the bucket level. Navigate to S3 > Bucket > Permissions > Block Public Access and enable all four settings.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-002",
    account_id: "acct-001",
    check_id: "rds_instance_storage_encrypted",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-analytics",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    title: "RDS instance storage is not encrypted",
    status: "fail",
    severity: "critical",
    compliance_type: "PCI-DSS",
    description: "The RDS instance 'xenkrypt-analytics' does not have storage encryption enabled. Unencrypted databases are vulnerable to data exposure if the underlying storage media is compromised.",
    recommendation: "Enable encryption at rest for the RDS instance. Note: You cannot enable encryption on an existing unencrypted instance. Create a new encrypted instance and migrate data.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-003",
    account_id: "acct-001",
    check_id: "iam_user_mfa_enabled",
    resource_id: "arn:aws:iam::491827364051:user/deploy-bot",
    resource_type: "AWS::IAM::User",
    service: "iam",
    region: "global",
    title: "IAM user does not have MFA enabled",
    status: "fail",
    severity: "critical",
    compliance_type: "CIS AWS",
    description: "The IAM user 'deploy-bot' does not have multi-factor authentication (MFA) enabled. Without MFA, the account is more susceptible to unauthorized access.",
    recommendation: "Enable MFA for the IAM user. For service accounts, consider using IAM roles with temporary credentials instead of long-lived access keys.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-004",
    account_id: "acct-001",
    check_id: "ec2_instance_public_ip",
    resource_id: "i-0e1f2a3b4c5d6e7f8",
    resource_type: "AWS::EC2::Instance",
    service: "ec2",
    region: "eu-west-1",
    title: "EC2 instance has a public IP assigned",
    status: "fail",
    severity: "high",
    compliance_type: "SOC2",
    description: "The EC2 instance 'bastion-eu' has a public IP address (54.72.31.198) directly assigned. Direct public exposure increases the attack surface.",
    recommendation: "Consider using a load balancer or VPN for access instead of direct public IP assignment. If a bastion host is required, restrict SSH access to known IP ranges only.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-005",
    account_id: "acct-001",
    check_id: "s3_bucket_logging_enabled",
    resource_id: "arn:aws:s3:::xenkrypt-logs-archive",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "eu-west-1",
    title: "S3 Bucket does not have server access logging enabled",
    status: "fail",
    severity: "high",
    compliance_type: "CIS AWS",
    description: "The S3 bucket 'xenkrypt-logs-archive' does not have server access logging enabled. Without access logging, it is difficult to track who accessed what data and when.",
    recommendation: "Enable server access logging for the S3 bucket. Configure a logging bucket to receive access logs.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-006",
    account_id: "acct-001",
    check_id: "s3_bucket_encryption",
    resource_id: "arn:aws:s3:::xenkrypt-logs-archive",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "eu-west-1",
    title: "S3 Bucket default encryption is not enabled",
    status: "fail",
    severity: "high",
    compliance_type: "HIPAA",
    description: "The S3 bucket 'xenkrypt-logs-archive' does not have default encryption enabled. Objects uploaded without explicit encryption will be stored unencrypted.",
    recommendation: "Enable default encryption for the S3 bucket using SSE-S3 or SSE-KMS. Navigate to S3 > Bucket > Properties > Default encryption.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-007",
    account_id: "acct-001",
    check_id: "rds_instance_multi_az",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-analytics",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    title: "RDS instance does not have Multi-AZ enabled",
    status: "fail",
    severity: "medium",
    compliance_type: "SOC2",
    description: "The RDS instance 'xenkrypt-analytics' is not configured for Multi-AZ deployment. A single-AZ deployment may result in downtime during maintenance or failure events.",
    recommendation: "Enable Multi-AZ deployment for the RDS instance to improve availability and fault tolerance.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-008",
    account_id: "acct-001",
    check_id: "iam_user_multiple_access_keys",
    resource_id: "arn:aws:iam::491827364051:user/deploy-bot",
    resource_type: "AWS::IAM::User",
    service: "iam",
    region: "global",
    title: "IAM user has multiple active access keys",
    status: "fail",
    severity: "medium",
    compliance_type: "CIS AWS",
    description: "The IAM user 'deploy-bot' has 2 active access keys. Having multiple active access keys increases the risk of key exposure and makes key rotation more complex.",
    recommendation: "Deactivate or delete unused access keys. Maintain only one active access key per IAM user and rotate keys regularly.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-009",
    account_id: "acct-001",
    check_id: "s3_bucket_versioning",
    resource_id: "arn:aws:s3:::xenkrypt-user-uploads",
    resource_type: "AWS::S3::Bucket",
    service: "s3",
    region: "us-east-1",
    title: "S3 Bucket versioning is not enabled",
    status: "fail",
    severity: "medium",
    compliance_type: null,
    description: "The S3 bucket 'xenkrypt-user-uploads' does not have versioning enabled. Without versioning, accidentally deleted or overwritten objects cannot be recovered.",
    recommendation: "Enable versioning for the S3 bucket to protect against accidental data loss.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-010",
    account_id: "acct-001",
    check_id: "rds_instance_backup_retention",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-analytics",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    title: "RDS backup retention period is less than 14 days",
    status: "fail",
    severity: "low",
    compliance_type: null,
    description: "The RDS instance 'xenkrypt-analytics' has a backup retention period of only 7 days. This may not provide sufficient recovery options for compliance or disaster recovery.",
    recommendation: "Increase the backup retention period to at least 14 days for production workloads.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-011",
    account_id: "acct-001",
    check_id: "ec2_instance_imdsv2",
    resource_id: "i-0a7b3c9d2e1f4a5b6",
    resource_type: "AWS::EC2::Instance",
    service: "ec2",
    region: "us-east-1",
    title: "EC2 instance is not enforcing IMDSv2",
    status: "fail",
    severity: "medium",
    compliance_type: "CIS AWS",
    description: "The EC2 instance 'api-server-01' allows IMDSv1 access. IMDSv1 is susceptible to SSRF attacks that could expose instance metadata and credentials.",
    recommendation: "Enforce IMDSv2 by setting HttpTokens to 'required' in the instance metadata options.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "FAIL" },
  },
  {
    id: "find-012",
    account_id: "acct-001",
    check_id: "vpc_flow_logs_enabled",
    resource_id: "vpc-0abc123def",
    resource_type: "AWS::EC2::VPC",
    service: "vpc",
    region: "us-east-1",
    title: "VPC Flow Logs are enabled",
    status: "pass",
    severity: "info",
    compliance_type: "CIS AWS",
    description: "The VPC 'xenkrypt-prod-vpc' has flow logging enabled, providing network traffic visibility.",
    recommendation: "No action needed. Continue monitoring flow logs for anomalous traffic patterns.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "PASS" },
  },
  {
    id: "find-013",
    account_id: "acct-001",
    check_id: "rds_instance_encrypted",
    resource_id: "arn:aws:rds:us-east-1:491827364051:db:xenkrypt-primary",
    resource_type: "AWS::RDS::DBInstance",
    service: "rds",
    region: "us-east-1",
    title: "RDS instance storage encryption is enabled",
    status: "pass",
    severity: "info",
    compliance_type: "PCI-DSS",
    description: "The RDS instance 'xenkrypt-primary' has storage encryption enabled with AWS KMS.",
    recommendation: "No action needed. Ensure KMS key rotation is enabled.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "PASS" },
  },
  {
    id: "find-014",
    account_id: "acct-001",
    check_id: "lambda_function_public_access",
    resource_id: "arn:aws:lambda:us-east-1:491827364051:function:xenkrypt-auth-handler",
    resource_type: "AWS::Lambda::Function",
    service: "lambda",
    region: "us-east-1",
    title: "Lambda function does not allow public access via resource policy",
    status: "pass",
    severity: "info",
    compliance_type: null,
    description: "The Lambda function 'xenkrypt-auth-handler' does not have a resource-based policy that allows public invocation.",
    recommendation: "No action needed.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "PASS" },
  },
  {
    id: "find-015",
    account_id: "acct-001",
    check_id: "sg_unrestricted_ssh",
    resource_id: "sg-0f9e8d7c6b",
    resource_type: "AWS::EC2::SecurityGroup",
    service: "vpc",
    region: "us-east-1",
    title: "Security group allows SSH from restricted IP range only",
    status: "pass",
    severity: "info",
    compliance_type: "CIS AWS",
    description: "The security group 'bastion-sg' restricts SSH (port 22) access to known IP ranges.",
    recommendation: "No action needed. Periodically review allowed IP ranges and remove stale entries.",
    updated_at: "2026-02-22T14:12:00Z",
    raw_data: { prowler_status: "PASS" },
  },
];

// Populate recent findings for dashboard (critical + high failing findings)
MOCK_DASHBOARD_DATA.recent_findings = MOCK_FINDINGS.filter(
  (f) => f.status === "fail" && (f.severity === "critical" || f.severity === "high"),
);

// ── Paginated Findings Helper ──────────────────────────────────────────────

export function getMockPaginatedFindings(options: {
  page: number;
  pageSize: number;
  severity?: string;
  service?: string;
  statuses?: string;
  status?: string;
}) {
  let filtered = [...MOCK_FINDINGS];

  if (options.statuses) {
    const allowed = options.statuses.split(",");
    filtered = filtered.filter((f) => allowed.includes(f.status));
  } else if (options.status) {
    filtered = filtered.filter((f) => f.status === options.status);
  }

  if (options.severity && options.severity !== "all") {
    filtered = filtered.filter((f) => f.severity === options.severity);
  }

  if (options.service && options.service !== "all") {
    filtered = filtered.filter((f) => f.service === options.service);
  }

  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / options.pageSize));
  const start = (options.page - 1) * options.pageSize;
  const items = filtered.slice(start, start + options.pageSize);

  return { items, total, page: options.page, page_size: options.pageSize, total_pages: totalPages };
}
